//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelISC210
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int scoreId { get; set; }
        public string PlayerName { get; set; }
        public double score { get; set; }
    }
}
