//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public long ID { get; set; }
        public Nullable<double> PosicionX { get; set; }
        public Nullable<double> PosicionY { get; set; }
        public string NombreJugador { get; set; }
        public Nullable<int> RecordActual { get; set; }
    }
}
